"""initial_postgresql_schema

Revision ID: a7d24c64d83e
Revises:
Create Date: 2026-03-28 05:00:26.596155

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7d24c64d83e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('shortname', sa.String(length=10), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('hrsday', sa.Float(), nullable=False),
    sa.Column('hrsweek', sa.Float(), nullable=False),
    sa.Column('hrsmonth', sa.Float(), nullable=False),
    sa.Column('workdays', sa.String(length=30), nullable=True),
    sa.Column('salutation', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('birthday', sa.String(length=10), nullable=True),
    sa.Column('empstart', sa.String(length=10), nullable=True),
    sa.Column('empend', sa.String(length=10), nullable=True),
    sa.Column('function', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('hide', sa.Boolean(), nullable=False),
    sa.Column('note1', sa.Text(), nullable=True),
    sa.Column('note2', sa.Text(), nullable=True),
    sa.Column('note3', sa.Text(), nullable=True),
    sa.Column('note4', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('shortname', sa.String(length=20), nullable=True),
    sa.Column('super_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('hide', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['super_id'], ['groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_group_assignment_unique', 'group_assignments', ['employee_id', 'group_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_group_assignment_unique', table_name='group_assignments')
    op.drop_table('group_assignments')
    op.drop_table('groups')
    op.drop_table('employees')
    op.drop_table('companies')
    # ### end Alembic commands ###
